[{'inst': 'fld f1, 0(x1)',
  'opcode': 0,
  'rd': 'f1',
  'rs1': 'x1',
  'rs2': None,
  'imm': '0',
  'issue': None,
  'read_operands': None,
  'execution_complete': None,
  'write_result': None,
  'read': None,
  'exec': None,
  'write': None},
 {'inst': 'fsd  f1, 50(x11)',
  'opcode': 1,
  'rd': 'f1',
  'rs1': 'x11',
  'rs2': None,
  'imm': '50',
  'issue': None,
  'read_operands': None,
  'execution_complete': None,
  'write_result': None,
  'read': None,
  'exec': None,
  'write': None}]