{'int1': {'Opcode': 0,
  'Busy': False,
  'Op': None,
  'Fi': None,
  'Fj': None,
  'Fk': None,
  'Qj': None,
  'Qk': None,
  'Rj': False,
  'Rk': False,
  'Cycles_left': 1,
  'Cycles': 1},
 'int2': {'Opcode': 0,
  'Busy': False,
  'Op': None,
  'Fi': None,
  'Fj': None,
  'Fk': None,
  'Qj': None,
  'Qk': None,
  'Rj': False,
  'Rk': False,
  'Cycles_left': 1,
  'Cycles': 1},
 'div1': {'Opcode': 3,
  'Busy': False,
  'Op': None,
  'Fi': None,
  'Fj': None,
  'Fk': None,
  'Qj': None,
  'Qk': None,
  'Rj': False,
  'Rk': False,
  'Cycles_left': 10,
  'Cycles': 10}}